### ISSUE TITLE
Add option to change default terminal emulator

### ISSUE THREAD

**Issue by codehz** [Opticos/gwsl#1]
So people can use Windows Terminal insteads of legacy terminal emulator

**Comment by Pololot64** [comment]
Do you mean the new Windows Terminal for running commands directly in a distro? I was not planning to do this but can look into it.

**Comment by codehz** [comment]
> Do you mean the new Windows Terminal for running commands directly in a distro? I was not planning to do this but can look into it.

I mean the shell button,
It can be implemented as execute `wt -p "distro name"`

**Comment by Pololot64** [comment]
Cool. I can do that. Thanks for the suggestion.
