### ISSUE TITLE
Flutter apps somehow not rendered correctly.

### ISSUE THREAD

**Issue by gochev** [Opticos/gwsl#10]
IF you run a flutter app on linux it will not run correctly, the taskbar is broken and it seems the painting is broken inside the app as well.

Steps:
1)install flutter for linux in WSL2.
2) shell > flutter create helloworld
3) shell > cd helloworld
4) shell > flutter run

It will be displayed like this : 

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/5537142/229722671-3bc7d1fe-846c-4aa4-8709-1915fac32386.png">

Everything else is displayed correctly - gedit or google-chrome as comparacement.

**Comment by Pololot64** [comment]
Did it start working?

**Comment by gochev** [comment]
yes it was because wslg was taking over gwsl lnstalled different wsl distro with no wslg enabled only gwsl and it worked

**Comment by Pololot64** [comment]
👍
