### ISSUE TITLE
Make keypad work like windows?

### ISSUE THREAD

**Issue by d3x0r** [Opticos/gwsl#4]
Most X terminals don't translate the windows keypad at all... This at least sends the right home/end/pgup/down etc keys when numlock is off, but when shift is held, it turns on numlock... shift is really only associated with alpha-lock not numlock... so shift-arrow keys on the numpad, with numlock off doesn't mark text.
Maybe this is actually an upstream issue with the X provider?

**Comment by Pololot64** [comment]
I am not completely understanding the issue but if it is a bug it is out of the scope of GWSL... The best would be to look here: https://sourceforge.net/projects/vcxsrv/

**Comment by d3x0r** [comment]
Just adding a note- did file an issue with vcxsrv.  https://sourceforge.net/p/vcxsrv/feature-requests/53/

**Comment by Pololot64** [comment]
I saw that.. I am actually curious though if changing keyboard layouts or models would help... I have been messing with layouts and maybe I can find something. I'll reopen. :)

**Comment by mi-hol** [comment]
Should this issue be transferred to Opticos/GWSL-Source repo?

**Comment by Pololot64** [comment]
Not this one. Too specific to vcxsrv and an issue was already made there.
