### ISSUE TITLE
Fresh WSL Installation, Failed to Initialize Script Manager (Registry Theme Crashing Bug)

### ISSUE THREAD

**Issue by Castone22** [Opticos/gwsl#5]
Just tried installing this though the windows store, when i try launching it i get:
```
failed to execute script manager
```
And the log shows
```
Traceback (most recent call last):
  File "manager.py", line 308, in <module>
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Pololot64** [comment]
Thanks for bringing this up! I actually have it fixed in the code and I will do my best to have a release soon. I am in the final stretches of school and I am prioritizing that.

**Comment by Castone22** [comment]
Cool, I just noticed no one had created an issue for it, so now at least people googling it will be led here.  Good luck with school.
