### ISSUE TITLE
How do I override High DPI scaling of 'vcxsrv.exe' ?

### ISSUE THREAD

**Issue by tshanli** [Opticos/gwsl#6]
I tried overriding the high DPI scaling property of 'vcxsrv.exe' in the app directory(*C:\Program Files\WindowsApps\28644OpticosStudios.GWSL_1.3.6.0_x64__r3mwbcqrwk84r\GWSL\VCXSRV\vcxsrv.exe*), but it didn't take any effect, but the original 'vcxsrv.exe' is effective, and the in-app 'hi-dpi' setting has just zoomed in screen(also didn't scale any dpi). Any solution?
![gwsl_vcxsrv](https://i.imgur.com/bDnLB1u.jpeg)
![ori_vcxsrv](https://i.imgur.com/o4kB0Su.jpg)

**Comment by Pololot64** [comment]
I am working on finding a solution to this but cannot find a workaround for the store version yet. It should work on the traditional installer version... Actually since you have access to your apps folder, try applying the settings to these two files:
![image](https://user-images.githubusercontent.com/31389383/99467886-53ab9700-290d-11eb-86bb-44eb7ce121bd.png)

**Comment by tshanli** [comment]
Yes, It works on applying high dpi settings to 'GWSL_vcxsrv.exe' of the installer version.Thanks.

**Comment by Pololot64** [comment]
No problem. I am glad it worked. I am trying to find a way to automate this too but I am not there yet.

**Comment by Pololot64** [comment]
I found a way to programmatically control this. I will try to implement it in a store build. I am unsure how it will work for the store version but it should be straightforward

**Comment by Pololot64** [comment]
I made a way to do this automatically in the github version of 1.3.7 that I released Friday. You simply right click the GWSL systray icon --> Dpi Scaling Mode --> Options. 
![image](https://user-images.githubusercontent.com/31389383/104851336-0a9aa380-58ba-11eb-852b-46d61fdc5123.png)

**Comment by tshanli** [comment]
Thanks for your work! I've tested it on my machine and everything runs well. And now we have the handy option, but not implemented for store version yet?

**Comment by Pololot64** [comment]
I have not found a way to implement it for the store yet unfortunately.

**Comment by Pololot64** [comment]
Update: I just found a way to implement it I think!

**Comment by mi-hol** [comment]
Should this be closed?
